version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    depends_on:
      - celery
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: ./celery.dockerfile
    depends_on:
      - redis
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"