version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    depends_on:
      - celery
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: ./celery.dockerfile
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./app:/app
    env_file:
      - .env

  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7.0.14-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
