version: '3.8'

services:
  reverse-proxy:
    image: nginx:stable-alpine3.20-perl
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: app.dockerfile
    depends_on:
      - celery
    env_file:
      - .env
    ports:
      - "8000"
    volumes:
      - ./app:/app

  celery:
    build:
      context: .
      dockerfile: ./celery.dockerfile
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env

  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7.0.14-jammy
    ports:
      - "27017:27017"
